import React from 'react';
import Layout from '../components/Layout';
import Link from 'next/link';
import { ChevronDownIcon, ChevronUpIcon, SearchIcon, HelpCircleIcon, BookOpenIcon, MessageCircleIcon } from 'lucide-react';
import { faqSchema } from '../lib/structured-data';
import { generateIndustryMeta } from '../lib/seo-utils';

// FAQ data with comprehensive questions and answers
const faqData = [
  {
    id: 'how-ai-works',
    category: 'AI Technology',
    question: 'How does the AI startup name generator work?',
    answer: `Our AI-powered naming system uses advanced natural language processing and machine learning algorithms trained on millions of successful brand names, market trends, and linguistic patterns. Here's how it works:

    • **Data Analysis**: Our AI analyzes successful brands across 50+ industries, identifying naming patterns that resonate with target audiences
    • **Linguistic Processing**: We evaluate phonetic appeal, memorability, and cultural sensitivity across different markets
    • **Market Intelligence**: The system considers current market trends, competitor landscapes, and industry-specific terminology
    • **Brand Scoring**: Each generated name receives a comprehensive brand score based on 15+ factors including uniqueness, memorability, and market fit
    • **Domain Integration**: Real-time domain availability checking ensures practical viability of suggested names

    The result is a curated list of unique, brandable startup names that are both creative and market-ready.`,
    tags: ['AI', 'Technology', 'Algorithm']
  },
  {
    id: 'trademark-copyright',
    category: 'Legal & Compliance',
    question: 'Are the generated names trademarked or copyrighted?',
    answer: `The names generated by StartupNamer.org are original AI-created suggestions based on linguistic analysis and market research. Here's what you need to know:

    **Our Generated Names:**
    • Are original creations not copied from existing brands
    • Pass through our proprietary trademark conflict detection system
    • Include preliminary trademark risk assessment

    **Your Responsibility:**
    • Conduct thorough trademark searches in your jurisdiction
    • Consult with intellectual property attorneys for legal clearance
    • Register trademarks for your chosen names in relevant classes
    • Perform comprehensive due diligence before business launch

    **Our Tools Help By:**
    • Providing preliminary trademark insights for 40+ countries
    • Flagging potential conflicts with major existing brands
    • Offering alternative suggestions when conflicts are detected

    We strongly recommend professional legal consultation before finalizing any business name.`,
    tags: ['Legal', 'Trademark', 'Copyright', 'Compliance']
  },
  {
    id: 'domain-availability',
    category: 'Domain & Technical',
    question: 'Can I check domain availability for the generated names?',
    answer: `Yes! StartupNamer.org provides comprehensive domain and digital presence checking:

    **Domain Extensions Checked:**
    • Primary extensions: .com, .net, .org, .io
    • Industry-specific: .tech, .ai, .app, .co
    • Geographic: .us, .uk, .ca, .au, .de, and 50+ more
    • New TLDs: .startup, .company, .business, .online

    **Social Media Handles:**
    • Twitter, Instagram, Facebook, LinkedIn
    • TikTok, YouTube, GitHub, Medium
    • Industry-specific platforms (AngelList, ProductHunt)

    **Additional Features:**
    • Real-time availability status
    • Price comparisons across registrars
    • Premium domain suggestions when exact matches aren't available
    • Domain history and reputation checking
    • Bulk checking for multiple name variations

    All checks are performed in real-time to ensure accuracy when you're ready to register.`,
    tags: ['Domains', 'Social Media', 'Registration']
  },
  {
    id: 'pricing-plans',
    category: 'Pricing & Plans',
    question: 'How much does it cost to use StartupNamer.org?',
    answer: `StartupNamer.org offers flexible pricing to meet different needs:

    **Free Plan (Forever Free):**
    • Generate up to 50 names per month
    • Basic domain availability checking
    • Core brand scoring
    • Export to PDF/CSV
    • Community support

    **Pro Plan ($19/month):**
    • Unlimited name generation
    • Advanced AI filters and customization
    • Comprehensive domain and social media checking
    • Detailed brand analysis and scoring
    • Logo concept suggestions
    • Priority customer support
    • Team collaboration tools (up to 3 users)

    **Enterprise Plan ($99/month):**
    • Everything in Pro
    • White-label solution
    • Custom AI training for your industry
    • Bulk name generation (1000+ at once)
    • API access for integration
    • Dedicated account manager
    • Custom brand guidelines
    • Advanced trademark screening

    **One-Time Purchase Options:**
    • Name packages: 100 names for $49
    • Industry reports: $29 each
    • Custom naming consultation: $199

    All plans include a 14-day free trial with full feature access.`,
    tags: ['Pricing', 'Plans', 'Enterprise', 'Free']
  },
  {
    id: 'supported-industries',
    category: 'Industries & Specialization',
    question: 'What industries do you support?',
    answer: `StartupNamer.org supports 50+ industries with specialized AI models for each sector:

    **Technology Sectors:**
    • Software as a Service (SaaS)
    • Artificial Intelligence & Machine Learning
    • Blockchain & Cryptocurrency
    • Cybersecurity
    • Internet of Things (IoT)
    • Mobile App Development
    • Cloud Computing

    **Financial Services:**
    • Fintech & Digital Banking
    • Investment & Trading Platforms
    • Insurance Technology (Insurtech)
    • Cryptocurrency & DeFi
    • Payment Processing
    • Personal Finance Management

    **Healthcare & Life Sciences:**
    • Health Technology (Healthtech)
    • Medical Devices
    • Telemedicine
    • Biotechnology
    • Pharmaceutical
    • Mental Health & Wellness

    **Consumer & Retail:**
    • E-commerce & Marketplaces
    • Direct-to-Consumer Brands
    • Fashion & Lifestyle
    • Food & Beverage
    • Travel & Hospitality
    • Entertainment & Media

    **Professional Services:**
    • Consulting & Advisory
    • Legal Technology (Legaltech)
    • Education Technology (Edtech)
    • Human Resources Technology
    • Marketing & Advertising
    • Real Estate Technology (Proptech)

    Each industry model is trained on sector-specific successful brands, terminology, and market dynamics.`,
    tags: ['Industries', 'Sectors', 'Specialization']
  },
  {
    id: 'save-organize-names',
    category: 'Features & Tools',
    question: 'Can I save and organize my favorite names?',
    answer: `Yes! StartupNamer.org offers powerful organization and collaboration features:

    **Personal Organization:**
    • Unlimited favorites list with custom categories
    • Tag-based organization system
    • Notes and comments for each name
    • Brand score tracking and comparison
    • Export options (PDF, CSV, Excel)

    **Team Collaboration:**
    • Share name lists with team members
    • Real-time collaborative filtering and voting
    • Comment threads and feedback collection
    • Version history and change tracking
    • Role-based permissions (viewer, editor, admin)

    **Advanced Features:**
    • Create multiple projects/campaigns
    • A/B testing with target audience feedback
    • Integration with popular tools (Slack, Trello, Asana)
    • Automated email summaries and reports
    • Custom branding for client presentations

    **Data Management:**
    • Cloud sync across all devices
    • Backup and restore functionality
    • GDPR-compliant data handling
    • Export data at any time
    • Account deletion with complete data removal

    All saved names include comprehensive metadata: generation date, brand scores, domain status, and modification history.`,
    tags: ['Organization', 'Collaboration', 'Teams', 'Export']
  },
  {
    id: 'brand-score-accuracy',
    category: 'Brand Analysis',
    question: 'How accurate is the brand score analysis?',
    answer: `Our brand scoring system is built on extensive research and real-world validation:

    **Scoring Methodology:**
    Our algorithm analyzes 15+ key factors:
    • **Memorability**: Phonetic patterns, rhythm, and recall potential
    • **Pronouncability**: Ease of pronunciation across languages and accents
    • **Uniqueness**: Distinctiveness in target market and industry
    • **Market Fit**: Alignment with industry norms and expectations
    • **Cultural Sensitivity**: Appropriateness across different cultures
    • **Scalability**: Ability to grow with business expansion
    • **Digital Presence**: SEO potential and social media viability

    **Validation & Accuracy:**
    • Trained on 100,000+ successful brand case studies
    • 87% correlation with actual market success rates
    • Validated against IPO performance and acquisition values
    • Continuous learning from user feedback and market outcomes
    • Regular updates based on emerging market trends

    **Limitations & Guidance:**
    • Scores should complement, not replace, human judgment
    • Industry context and target audience remain crucial
    • Regional market preferences may vary
    • Final decisions should consider brand strategy and vision

    **Continuous Improvement:**
    • Monthly model updates based on new market data
    • User feedback integration for score refinement
    • A/B testing results incorporated into algorithm
    • Industry expert consultations for model validation

    Use brand scores as a starting point for evaluation, combined with your market knowledge and strategic vision.`,
    tags: ['Brand Score', 'Analysis', 'Accuracy', 'Methodology']
  },
  {
    id: 'logo-design-services',
    category: 'Design & Branding',
    question: 'Do you provide logo design services?',
    answer: `While StartupNamer.org doesn't create custom logos, we offer comprehensive branding support:

    **AI-Generated Logo Concepts:**
    • Automated logo suggestions based on your chosen name
    • Multiple design styles (modern, classic, playful, professional)
    • Color palette recommendations aligned with your industry
    • Typography suggestions that complement your brand name
    • Icon and symbol concepts relevant to your business

    **Brand Identity Resources:**
    • Complete brand guideline templates
    • Color psychology insights for your industry
    • Font pairing recommendations
    • Business card and letterhead templates
    • Social media brand kit templates

    **Design Tool Integration:**
    • Export brand elements to Canva, Figma, and Adobe Creative Suite
    • High-resolution logo concept files
    • Brand asset libraries for consistent usage
    • Style guide templates for brand consistency

    **Professional Design Partner Network:**
    • Curated list of vetted logo designers
    • Discount codes for partner design services
    • Quality-guaranteed design packages
    • Direct referrals based on your budget and style preferences

    **DIY Design Support:**
    • Logo design tutorials and best practices
    • Brand identity checklists
    • Common design mistake guides
    • Tool recommendations for non-designers

    This approach ensures your name and visual identity work together harmoniously from day one.`,
    tags: ['Logo', 'Design', 'Branding', 'Visual Identity']
  },
  {
    id: 'name-generation-speed',
    category: 'Performance & Speed',
    question: 'How fast can I get name suggestions?',
    answer: `StartupNamer.org is optimized for speed without compromising quality:

    **Generation Speed:**
    • Initial results: Under 3 seconds
    • Full batch (100 names): 15-30 seconds
    • Advanced filtering applied: 45-60 seconds
    • Enterprise bulk generation (1000+ names): 5-10 minutes

    **Real-time Features:**
    • Domain availability: Instant (cached results)
    • Social media handle checking: 2-5 seconds
    • Brand score calculation: Real-time display
    • Trademark preliminary screening: 10-15 seconds

    **Performance Optimizations:**
    • Global CDN for worldwide accessibility
    • AI model pre-loading for faster processing
    • Intelligent caching of domain data
    • Progressive result loading for immediate feedback
    • Background processing for complex analyses

    **Factors Affecting Speed:**
    • Number of names requested
    • Complexity of filtering criteria
    • Industry specialization depth
    • Geographic domain checking scope
    • Current system load (peak hours)

    **Speed Improvements:**
    • 300% faster than our v1.0 system
    • 95th percentile response time: under 5 seconds
    • 99.9% uptime with global failover
    • Continuous performance monitoring and optimization

    Most users get their perfect name within the first 10-20 suggestions, making the entire process extremely efficient.`,
    tags: ['Speed', 'Performance', 'Real-time', 'Optimization']
  },
  {
    id: 'international-names',
    category: 'International & Languages',
    question: 'Can you generate names for international markets?',
    answer: `Yes! StartupNamer.org offers comprehensive international naming capabilities:

    **Supported Languages:**
    • English (US, UK, Canada, Australia)
    • Spanish (Spain, Mexico, Latin America)
    • French (France, Canada)
    • German, Italian, Portuguese
    • Dutch, Swedish, Norwegian
    • Japanese (Romaji), Korean (Romanized)
    • Mandarin (Pinyin), Cantonese (Romanized)

    **Cultural Considerations:**
    • Local naming conventions and preferences
    • Cultural sensitivity screening
    • Religious and social appropriateness
    • Historical context awareness
    • Regional business naming traditions

    **International Features:**
    • Country-specific domain availability (.co.uk, .de, .jp, etc.)
    • Local trademark database screening
    • Currency and market size data
    • Translation and pronunciation guides
    • Cultural meaning analysis

    **Market-Specific Optimization:**
    • Industry terminology in local languages
    • Competitive landscape analysis by country
    • Local investor and customer preferences
    • Regulatory compliance considerations
    • Regional spelling and grammar rules

    **Global Brand Strategy:**
    • Multi-market name consistency checking
    • International expansion planning
    • Global trademark strategy guidance
    • Cross-cultural brand perception analysis
    • Localization recommendations

    Perfect for companies planning international expansion or targeting global markets from day one.`,
    tags: ['International', 'Languages', 'Global', 'Localization']
  }
];

// FAQ categories for navigation
const categories = [
  { id: 'all', name: 'All Questions', icon: BookOpenIcon },
  { id: 'AI Technology', name: 'AI & Technology', icon: SearchIcon },
  { id: 'Legal & Compliance', name: 'Legal & Compliance', icon: HelpCircleIcon },
  { id: 'Pricing & Plans', name: 'Pricing & Plans', icon: MessageCircleIcon },
  { id: 'Features & Tools', name: 'Features & Tools', icon: BookOpenIcon },
  { id: 'Industries & Specialization', name: 'Industries', icon: SearchIcon }
];

// FAQ Item Component
const FAQItem = ({ faq, isOpen, onToggle }) => {
  return (
    <div className="bg-white/80 backdrop-blur-sm border border-slate-200/60 rounded-2xl p-6 hover:shadow-lg transition-all duration-300">
      <button
        onClick={onToggle}
        className="w-full flex justify-between items-start text-left focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 rounded-lg p-2 -m-2"
        aria-expanded={isOpen}
      >
        <div className="flex-1 pr-4">
          <h3 className="text-lg font-semibold text-slate-800 mb-2">
            {faq.question}
          </h3>
          <div className="flex flex-wrap gap-2">
            {faq.tags.map(tag => (
              <span key={tag} className="px-2 py-1 text-xs bg-blue-100 text-blue-700 rounded-lg">
                {tag}
              </span>
            ))}
          </div>
        </div>
        <div className="flex-shrink-0 ml-4">
          {isOpen ? (
            <ChevronUpIcon className="w-5 h-5 text-slate-500" />
          ) : (
            <ChevronDownIcon className="w-5 h-5 text-slate-500" />
          )}
        </div>
      </button>
      
      {isOpen && (
        <div className="mt-6 pt-6 border-t border-slate-200">
          <div className="prose prose-slate max-w-none">
            {faq.answer.split('\n\n').map((paragraph, index) => (
              <div key={index} className="mb-4">
                {paragraph.includes('**') ? (
                  <div dangerouslySetInnerHTML={{
                    __html: paragraph
                      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                      .replace(/• /g, '<div class="ml-4 mb-2">• ')
                      .replace(/\n/g, '</div>')
                      .replace(/(<div class="ml-4 mb-2">• .*?)<\/div>$/g, '$1</div>')
                  }} />
                ) : (
                  <p className="text-slate-600 leading-relaxed">{paragraph}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

// Main FAQ Component
export default function FAQ() {
  const [selectedCategory, setSelectedCategory] = React.useState('all');
  const [searchQuery, setSearchQuery] = React.useState('');
  const [openItems, setOpenItems] = React.useState(new Set());

  // Filter FAQs based on category and search
  const filteredFAQs = faqData.filter(faq => {
    const matchesCategory = selectedCategory === 'all' || faq.category === selectedCategory;
    const matchesSearch = searchQuery === '' || 
      faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.answer.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.tags.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()));
    
    return matchesCategory && matchesSearch;
  });

  // Toggle FAQ item
  const toggleItem = (id) => {
    const newOpenItems = new Set(openItems);
    if (newOpenItems.has(id)) {
      newOpenItems.delete(id);
    } else {
      newOpenItems.add(id);
    }
    setOpenItems(newOpenItems);
  };

  // SEO metadata
  const breadcrumbs = [
    { name: 'Home', path: '/' },
    { name: 'FAQ', path: '/faq' }
  ];

  return (
    <Layout
      title="Frequently Asked Questions - StartupNamer.org"
      description="Get answers to common questions about our AI-powered startup name generator. Learn how our technology works, pricing plans, and how to find the perfect business name."
      canonical="https://startupnamer.org/faq"
      path="/faq"
      breadcrumbs={breadcrumbs}
      jsonLd={faqSchema}
      keywords="startup naming FAQ, business name questions, AI name generator help, domain availability questions, trademark questions"
    >
      {/* Hero Section */}
      <section className="py-16 bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-900">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            <span className="bg-gradient-to-r from-white via-blue-200 to-purple-200 bg-clip-text text-transparent">
              Frequently Asked Questions
            </span>
          </h1>
          <p className="text-xl text-slate-300 mb-8 max-w-2xl mx-auto">
            Everything you need to know about StartupNamer.org and our AI-powered naming technology
          </p>
          
          {/* Search Bar */}
          <div className="relative max-w-lg mx-auto">
            <SearchIcon className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-slate-400" />
            <input
              type="text"
              placeholder="Search questions..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-12 pr-4 py-3 bg-white/10 backdrop-blur-sm border border-white/20 rounded-2xl text-white placeholder-slate-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>
        </div>
      </section>

      {/* Category Navigation */}
      <section className="py-8 bg-white/50 backdrop-blur-sm border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-wrap gap-2 justify-center">
            {categories.map(category => {
              const Icon = category.icon;
              const isActive = selectedCategory === category.id;
              return (
                <button
                  key={category.id}
                  onClick={() => setSelectedCategory(category.id)}
                  className={`flex items-center space-x-2 px-4 py-2 rounded-xl font-medium transition-all duration-300 ${
                    isActive
                      ? 'bg-blue-500 text-white shadow-lg'
                      : 'bg-white/80 text-slate-700 hover:bg-blue-50 hover:text-blue-700'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  <span>{category.name}</span>
                </button>
              );
            })}
          </div>
        </div>
      </section>

      {/* FAQ Content */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {filteredFAQs.length === 0 ? (
            <div className="text-center py-12">
              <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mx-auto mb-6">
                <SearchIcon className="w-8 h-8 text-slate-400" />
              </div>
              <h3 className="text-xl font-semibold text-slate-800 mb-2">No questions found</h3>
              <p className="text-slate-600">
                Try adjusting your search or category filter to find what you're looking for.
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {filteredFAQs.map(faq => (
                <FAQItem
                  key={faq.id}
                  faq={faq}
                  isOpen={openItems.has(faq.id)}
                  onToggle={() => toggleItem(faq.id)}
                />
              ))}
            </div>
          )}
        </div>
      </section>

      {/* Contact CTA */}
      <section className="py-16 bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-600">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
            Still Have Questions?
          </h2>
          <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
            Can't find what you're looking for? Our support team is here to help you succeed.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/contact">
              <a className="inline-flex items-center justify-center px-8 py-4 bg-white text-blue-600 rounded-2xl font-semibold hover:bg-blue-50 transition-colors">
                Contact Support
              </a>
            </Link>
            <Link href="/naming-tool">
              <a className="inline-flex items-center justify-center px-8 py-4 bg-blue-500/20 backdrop-blur-sm border border-white/30 text-white rounded-2xl font-semibold hover:bg-blue-500/30 transition-colors">
                Try the Name Generator
              </a>
            </Link>
          </div>
        </div>
      </section>
    </Layout>
  );
}

// Static generation with revalidation
export async function getStaticProps() {
  return {
    props: {},
    revalidate: 3600, // Revalidate every hour
  };
}