# Version of the agent configuration standard
version = "1.0"

# Default model for all agents
model = "claude-4-sonnet"

# Global instructions for startupnameai project context
instructions = """
You are working on Startupnamer.org, a business start up name service


Always consider the positioning and value delivery in your responses.
"""

# Import all agent configurations
imports = [
    "agents/emily.toml",
    "agents/morgan.toml",
    "agents/casey.toml",
    "agents/jules.toml",
    "agents/riley.toml",
    "agents/shane.toml",
    "agents/alex.toml",
    "agents/quinn.toml",
    "agents/taylor.toml",
    "agents/atlas.toml",
    "agents/blake.toml",
    "agents/hudson.toml",
    "agents/cora.toml",
    "agents/frank.toml"]