# Version of the agent configuration standard
version = "1.0"

# Default model for all agents
model = "claude-3-5-sonnet-20241022"

# Global instructions for Startupnamer.org project context
instructions = """
You are working on startupnamer.org interface

Key Context:
- Project location: C:\Users\Ben\OneDrive\Documents\startupnameai
- Pricing: 
-Starter- $39
-Professional- $79
-Enterprise- $159


Always consider the positioning and value delivery in your responses.
"""

# Import all agent configurations
imports = [
    "agents/emily.toml",
    "agents/morgan.toml",
    "agents/casey.toml",
    "agents/jules.toml",
    "agents/riley.toml",
    "agents/shane.toml",
    "agents/alex.toml",
    "agents/quinn.toml",
    "agents/taylor.toml",
    "agents/atlas.toml",
    "agents/blake.toml",
    "agents/hudson.toml",
    "agents/cora.toml"