cd "C:\Users\Ben\OneDrive\Documents\GitHub\StartupNameAI"

# Remove the broken file
rm agent.toml

# Create a properly formatted agent.toml
cat > agent.toml << 'EOF'
version = "1.0"
model = "claude-4-sonnet"

instructions = """
You are working on StartupNamer.org, an AI-powered startup naming platform.

Key Context:
- Project location: C:\Users\Ben\OneDrive\Documents\GitHub\StartupNameAI
- Technology: React, Node.js, OpenAI, Stripe, Netlify
- Domain: startupnamer.org (The Startup Naming Authority)
- Value proposition: AI-powered startup name generation with domain checking

Always consider the professional positioning and AI-powered value delivery in your responses.
"""

imports = [
  "agents/emily.toml",
    "agents/morgan.toml", 
    "agents/casey.toml",
    "agents/jules.toml",
    "agents/riley.toml",
    "agents/shane.toml",
    "agents/alex.toml",
    "agents/quinn.toml",
    "agents/taylor.toml",
    "agents/atlas.toml",
    "agents/blake.toml", 
    "agents/hudson.toml",
    "agents/cora.toml",
    "agents/debugger.toml"
]
EOF
