[build]
  base = "client"
  command = "npm install --legacy-peer-deps --no-audit --no-fund && npm run build"
  publish = "client/build"
  environment = { NODE_VERSION = "16.18.1", NPM_VERSION = "8.19.4", NODE_OPTIONS = "" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
