[build]
  base = "client/"
  publish = "client/build/"
  command = "npm install --no-audit --no-fund && CI=false GENERATE_SOURCEMAP=false DISABLE_ESLINT_PLUGIN=true npx react-scripts build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
