[build]
  base = "client"
  command = "npm install --legacy-peer-deps --no-audit --no-fund && npm run build"
  publish = "client/build"
  environment = { NODE_VERSION = "18.18.0", NPM_VERSION = "9.8.1", NODE_OPTIONS = "--max-old-space-size=4096", NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
