[build]
  base = "client"
  command = "npm ci --no-audit --no-fund --prefer-offline && npm run build"
  publish = "client/build"
  environment = { NODE_VERSION = "16.18.1", NPM_VERSION = "8.19.4", NODE_OPTIONS = "--max-old-space-size=4096", NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
