[build]
  # Build INSIDE the client folder
  base = "client"
  command = "npm ci && npm run build:snap"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  # Make sure Netlify doesn't inject conflicting npm flags:
  NPM_FLAGS = ""
